"""Common configuration constants
"""

PROJECTNAME = 'wres.archetypes'

ADD_PERMISSIONS = {
    # -*- extra stuff goes here -*-
    'Visit': 'wres.archetypes: Add Visit',
    'Impresso': 'wres.archetypes: Add Impresso',
    'Template': 'wres.archetypes: Add Template',
    'TemplateFolder': 'wres.archetypes: Add TemplateFolder',
    'GenericDocument': 'wres.archetypes: Add GenericDocument',
    'MedicalDocument': 'wres.archetypes: Add MedicalDocument',
    'UploadChartFolder': 'wres.archetypes: Add UploadChartFolder',
    'ReviewOfSystems': 'wres.archetypes: Add ReviewOfSystems',
    'Clinic': 'wres.archetypes: Add Clinic',
    'Encounter': 'wres.archetypes: Add Encounter',
    'VisitTemp': 'wres.archetypes: Add VisitTemp',
    'Visit': 'wres.archetypes: Add Visit',
    'InsuranceFolder': 'wres.archetypes: Add InsuranceFolder',
    'Insurance': 'wres.archetypes: Add Insurance',
    'InitialVisit': 'wres.archetypes: Add InitialVisit',
    'Visit': 'wres.archetypes: Add Visit',
    'VisitFolder': 'wres.archetypes: Add VisitFolder',
    'ProgressNotes': 'wres.archetypes: Add ProgressNotes',
    'ReferringProviderFolder': 'wres.archetypes: Add ReferringProviderFolder',
    'ReferringProvider': 'wres.archetypes: Add ReferringProvider',
    'AdminFolder': 'wres.archetypes: Add AdminFolder',
    'Admin': 'wres.archetypes: Add Admin',
    'DocPlastica': 'wres.archetypes: Add DocPlastica',
    'DocBoletim': 'wres.archetypes: Add DocBoletim',
    'ExamFolder': 'wres.archetypes: Add ExamFolder',
    'DocumentFolder': 'wres.archetypes: Add DocumentFolder',
    'ChartFolder': 'wres.archetypes: Add ChartFolder',
    'WRESUser': 'wres.archetypes: Add WRESUser',
    'TranscriptionistFolder': 'wres.archetypes: Add TranscriptionistFolder',
    'Transcriptionist': 'wres.archetypes: Add Transcriptionist',
    'SecretaryFolder': 'wres.archetypes: Add SecretaryFolder',
    'Secretary': 'wres.archetypes: Add Secretary',
    'Patient': 'wres.archetypes: Add Patient',
    'Doctor': 'wres.archetypes: Add Doctor',
    'PatientFolder': 'wres.archetypes: Add PatientFolder',
    'Patient': 'wres.archetypes: Add Patient',
    'DoctorFolder': 'wres.archetypes: Add DoctorFolder',
    'Doctor': 'wres.archetypes: Add Doctor',
}
