# -*- extra stuff goes here -*-
from impresso import IImpresso
from template import ITemplate
from templatefolder import ITemplateFolder
from genericdocument import IGenericDocument
from medicaldocument import IMedicalDocument
from uploadchartfolder import IUploadChartFolder
from reviewofsystems import IReviewOfSystems
from clinic import IClinic
from encounter import IEncounter
from visittemp import IVisitTemp
from insurancefolder import IInsuranceFolder
from insurance import IInsurance
from visitfolder import IVisitFolder
from adminfolder import IAdminFolder
from admin import IAdmin
from documentfolder import IDocumentFolder
from chartfolder import IChartFolder
from wresuser import IWRESUser
from secretaryfolder import ISecretaryFolder
from secretary import ISecretary
from patient import IPatient
from doctor import IDoctor
from patientfolder import IPatientFolder
from patient import IPatient
from doctorfolder import IDoctorFolder
from doctor import IDoctor
